on:
  workflow_dispatch:
  
env:
  PACKAGE_NAME: aikatsu_aoi_discord_bot_v2
  OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Delete untagged images
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.request("GET /users/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            console.log(response)
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /users/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id);
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: ${{ env.OWNER }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          PER_PAGE: 100